DMCE/CMS/urls.py
from django.conf.urls import url
from CMS import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^contacto/$', views.contact, name="contact"),
    url(r'^aviso-legal/$', views.legal, name="legal"),
    url(r'^sobre-nosotros/$', views.about, name="about"),
    url(r'^(?P<slug>[\w-]+)/$', views.dispatch_slug, name="dispatch_slug"),
]

DMCE/DMCE/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static, serve
from django.contrib.auth import views as auth_views
from ecommerce.views import account, activate_view, auth_view, logout_view, sing_up_view, login_view

urlpatterns = [
    url(r'^sermepa/', include('sermepa.urls')),
    url(r'^jet/', include('jet.urls', 'jet')), 
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_ROOT }), 
    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT, }), 
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate_view, name='activate'),
    url(r'^auth/', auth_view, name="auth"),
    url(r'^login/', login_view, name="login"),
    url(r'^logout/', logout_view, name="logout"),
    url(r'^sing_up/', sing_up_view, name="sing_up"),
    url(r'^cuenta/', account, name="account"),
    url(r'^tienda/', include('ecommerce.urls', namespace='ecommerce')),
    url(r'', include('CMS.urls')),
]

DMCE/ecommerce/urls.py
from django.conf.urls import url
from ecommerce import views

urlpatterns = [
    url(r'^$', views.general, name="general"),
    url(r'^edit_cart/', views.edit_cart, name="edit_cart"),
    url(r'^carrito/', views.cart, name="my_cart"),
    url(r'^compra/', views.checkout, name="checkout"),
    url(r'^payment/', views.payment, name="payment"),
    url(r'^(?P<slug>[\w-]+)/$', views.dispatch_slug, name="dispatch_slug"),
]

DMCE/jet/urls.py
import django
from django.conf.urls import url

try:
    from django.views.i18n import JavaScriptCatalog
    javascript_catalog = JavaScriptCatalog.as_view()
except ImportError:  # Django < 2.0
    from django.views.i18n import javascript_catalog

from jet.views import add_bookmark_view, remove_bookmark_view, toggle_application_pin_view, model_lookup_view


app_name = 'jet'

urlpatterns = [
    url(
        r'^add_bookmark/$',
        add_bookmark_view,
        name='add_bookmark'
    ),
    url(
        r'^remove_bookmark/$',
        remove_bookmark_view,
        name='remove_bookmark'
    ),
    url(
        r'^toggle_application_pin/$',
        toggle_application_pin_view,
        name='toggle_application_pin'
    ),
    url(
        r'^model_lookup/$',
        model_lookup_view,
        name='model_lookup'
    ),
    url(
        r'^jsi18n/$',
        javascript_catalog,
        {'packages': 'django.contrib.admin+jet'},
        name='jsi18n'
    ),
]

if django.VERSION[:2] < (1, 8):
    from django.conf.urls import patterns
    urlpatterns = patterns('', *urlpatterns)

DMCE/ecommerce/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Client, Order, HOUR_CHOICES, DAY_CHOICES
from django import forms
from django.utils.encoding import force_text


class SignUpForm(UserCreationForm):
    
    email = forms.EmailField(max_length=254)

    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError("Ya existe un usuario con este email.")
        return data

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)

class ClientForm(forms.ModelForm):
    firstname = forms.CharField(label="Nombre")
    lastname = forms.CharField(label="Apellidos")
    phone = forms.CharField(label="Teléfono")
    country = forms.CharField(label="País")
    city = forms.CharField(label="Ciudad")
    postal_code = forms.CharField(label="Código Postal")
    address = forms.CharField(label="Dirección")
    card_id = forms.CharField(label=u'DNI/NIF/CIF')


    class Meta:
        model = Client
        fields = ('firstname', 'lastname', 'phone', 'country', 'city', 'postal_code', 'address', 'card_id')



class OrderForm(forms.Form):
    inv_firstname = forms.CharField(label="Nombre", required=True)
    #inv_lastname = forms.CharField(label="Apellidos", required=True)
    inv_phone = forms.CharField(label=u"Teléfono", required=True)
    #inv_country = forms.CharField(label=u"País", required=True)
    #inv_city = forms.CharField(label="Ciudad", required=True)
    #inv_postal_code = forms.CharField(label="Código Postal", required=True)
    #inv_address = forms.CharField(label=u"Dirección", required=True)
    inv_email = forms.EmailField(label=u'Correo electrónico', required=True)
    inv_card_id = forms.CharField(label=u'DNI/NIF/CIF', required=True)

    hour_collection = forms.ChoiceField(label=u'Hora de recogida', choices=HOUR_CHOICES, required=True)
    day_collection = forms.ChoiceField(label=u'Día de recogida', choices=DAY_CHOICES, required=True)
    notes = forms.CharField(label="Notas sobre el pedido", widget=forms.Textarea(attrs={'cols' : "49", 'rows': "5", }), required=False)
    #dif_ship = forms.BooleanField(label=u"Los datos de envío no coinciden con los de facturación", required=False)
    
    ship_firstname = forms.CharField(label="Nombre", widget=forms.HiddenInput(), required=False)
    #ship_lastname = forms.CharField(label="Apellidos", required=False)
    ship_phone = forms.CharField(label="Teléfono", required=False)
    #ship_country = forms.CharField(label="País", required=False)
    #ship_city = forms.CharField(label="Ciudad", required=False)
    #ship_postal_code = forms.CharField(label="Código Postal", required=False)
    #ship_address = forms.CharField(label="Dirección", required=False)
    ship_email = forms.EmailField(label=u'Correo electrónico', required=False)

    #añadir placeholders
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['inv_firstname'].widget.attrs.update({'placeholder': 'Nombre'})
        self.fields['inv_phone'].widget.attrs.update({'placeholder': 'Teléfono'})
        self.fields['inv_email'].widget.attrs.update({'placeholder': 'Email'})
        self.fields['inv_card_id'].widget.attrs.update({'placeholder': 'DNI/CIF/NIF'})
        self.fields['notes'].widget.attrs.update({'placeholder': 'Notas sobre la reserva'})
    

DMCE/ecommerce/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from ecommerce.models import *
from ecommerce.forms import *
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from sermepa.models import SermepaIdTPV
from sermepa.forms import SermepaPaymentForm
from sermepa.signals import payment_was_successful
from django.core.mail import EmailMessage
from datetime import date
from django.contrib.sites.models import Site
from django.contrib.sites.shortcuts import get_current_site
from django.conf import settings
from django.core.paginator import Paginator
from CMS.models import Config
from django.views.decorators.csrf import csrf_exempt
from ecommerce.tokens import account_activation_token
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm

"""ECOMMERCE VIEWS"""

def general(request):
    products = Product.objects.all()
    categories = Category.objects.all()

    return render(request, "ecommerce/general.html", locals())


def dispatch_slug(request, slug):
    #import ipdb; ipdb.set_trace()
    categories = Category.objects.all()
    #Products in cart
    if 'cart' in request.session and len(request.session['cart'].keys()) > 0:
        cart_items = Product.objects.filter(id__in = request.session['cart'].keys())
        cart_items = [(product, request.session['cart'][str(product.id)]) for product in cart_items]
        cart_tam = len(cart_items)


    slug = get_object_or_404(Slug, slug=slug)
    qs = Product.objects.filter(slug=slug)
    if qs.exists():
        product = qs[0]
        return render(request, "ecommerce/product.html", locals())   
    qs = Category.objects.filter(slug=slug)
    if qs.exists():
        content = qs[0] #contiene la categoria
        products_cat = Product.objects.filter(category=content.slug_id)
        cat = True
        return render(request, "ecommerce/general.html", locals())


def account(request):
    a_form = AuthenticationForm()
    su_form = SingUpForm()
    return render(request, "ecommerce/account.html", locals())


def cart(request):    
    categories = Category.objects.all()
    if 'cart' in request.session and len(request.session['cart'].keys()) > 0:
        cart_items = Product.objects.filter(id__in = request.session['cart'].keys())
        cart_subtotal = sum([product.price*request.session['cart'][str(product.id)] for product in cart_items])
        cart_items = [(product, request.session['cart'][str(product.id)]) for product in cart_items]
        cart_tam = len(cart_items)
        return render(request, "ecommerce/cart.html", locals())
    else:
        return HttpResponseRedirect('/')


@csrf_exempt
def edit_cart(request):
    categories = Category.objects.all()
    #data={}
    #if request.is_ajax():
    #si la cantidad viene en el post se asignara ese valor, sino se le asignara 1
    quantity = int(request.POST['quantity']) if 'quantity' in request.POST else 1
    #Añadir productos
    if 'add_product' in request.POST:
        if 'cart' in request.session:
            cart_dict = request.session['cart']
            cart_dict.update({request.POST['add_product']: quantity})
            request.session['cart'] = {}
            request.session['cart'] = cart_dict
        else:
            cart_dict = {}
            cart_dict[request.POST['add_product']] = quantity
            request.session['cart'] = {}
            request.session['cart'] = cart_dict
    #Eliminar producto
    elif 'del_product' in request.POST:
        del_product = request.POST['del_product']
        cart_dict = request.session['cart']
        cart_dict = {key: val for key, val in cart_dict.items() if key != del_product}    
        request.session['cart'] = {}
        request.session['cart'] = cart_dict  
    #Actualizar cantidad productos  
    elif 'upt_qty' in request.POST:
        upt_qty = int(request.POST['upt_qty'])
        cart_dict = request.session['cart']
        for key, val in cart_dict.items(): cart_dict.update({request.POST['update_product']: upt_qty})
        request.session['cart'] = {}
        request.session['cart'] = cart_dict   

    #Products in cart
    if 'cart' in request.session and len(request.session['cart'].keys()) > 0:
        cart_items = Product.objects.filter(id__in = request.session['cart'].keys())
        cart_items = [(product, request.session['cart'][str(product.id)]) for product in cart_items]
        cart_tam = len(cart_items)

    return render(request, "ecommerce/cart.html", locals())


def checkout(request):  
    if 'cart' in request.session and len(request.session['cart'].keys()) > 0:
        if request.user.is_anonymous:
            o_form = OrderForm()
        else:
            o_form = OrderForm(
                        initial={
                                'inv_firstname' : request.user.profile.firstname,
                                'inv_phone' : request.user.profile.phone,
                                'inv_email' : request.user.email,
                                'inv_card_id' : request.user.profile.card_id,
                                }
                            )

        cart_items = Product.objects.filter(id__in = request.session['cart'].keys())
        cart_subtotal = sum([product.price*request.session['cart'][str(product.id)] for product in cart_items])
        cart_items = [(product, request.session['cart'][str(product.id)]) for product in cart_items]
        
        return render(request, "ecommerce/checkout.html", locals())
    else:
        return HttpResponseRedirect('/')


@csrf_exempt
def payment(request):
    #data={}
    config = Config.objects.all()[0]
    #if request.is_ajax():
    cart_items = Product.objects.filter(id__in = request.session['cart'].keys())
    cart_subtotal = sum([product.price*request.session['cart'][str(product.id)] for product in cart_items])
    amount = cart_subtotal*100

    if request.POST['ship_firstname'] == "":
        order = Order(
                inv_firstname = request.POST['inv_firstname'],
                inv_phone = request.POST['inv_phone'],
                inv_email = request.POST['inv_email'],
                inv_card_id = request.POST['inv_card_id'],

                ship_firstname = request.POST['inv_firstname'],
                ship_phone = request.POST['inv_phone'],
                ship_email = request.POST['inv_email'],

                hour_collection = request.POST['hour_collection'],
                day_collection = request.POST['day_collection'],

                total = amount/100,
                client = request.user.profile if not request.user.is_anonymous else None,
                notes = request.POST['notes'],
                products ='/'.join(str(e) for e in [(product.id, product.price, request.session['cart'][str(product.id)]) for product in cart_items]),
                status = 'R',
                )
        order.save()
    else:
        order = Order(
                inv_firstname = request.POST['inv_firstname'],
                inv_phone = request.POST['inv_phone'],
                inv_email = request.POST['inv_email'],
                inv_card_id = request.POST['inv_card_id'],

                ship_firstname = request.POST['ship_firstname '],
                ship_phone = request.POST['ship_phone'],
                ship_email = request.POST['ship_email'],
                ship_card_id = request.POST['ship_card_id'],

                hour_collection = request.POST['hour_collection'],
                day_collection = request.POST['day_collection'],

                total = amount/100,
                client = request.user.profile if not request.user.is_anonymous else None,
                notes = request.POST['notes'],
                products ='/'.join(str(e) for e in [(product.id, product.price, request.session['cart'][str(product.id)]) for product in cart_items]),
                status = 'R',
                )
        order.save()
    
    #site = Site.objects.get_current()
    """
    sermepa_dict = {
        "Ds_Merchant_Titular": 'TITULAR',
        "Ds_Merchant_MerchantData": order.id, # id del Pedido o Carrito, para identificarlo en el mensaje de vuelta
        "Ds_Merchant_MerchantName": 'nombredelnegorio',
        "Ds_Merchant_ProductDescription": u'Compra de productos',
        "Ds_Merchant_Amount": int(amount),
        "Ds_Merchant_Terminal": settings.SERMEPA_TERMINAL,
        "Ds_Merchant_MerchantCode": settings.SERMEPA_MERCHANT_CODE,
        "Ds_Merchant_Currency": settings.SERMEPA_CURRENCY,
        "Ds_Merchant_MerchantURL": "https://%s%s" % (site.domain, reverse('sermepa_ipn')),
        "Ds_Merchant_UrlOK": "https://%s/tienda/pedido/%s?fr=True" % (site.domain, order.ref_token),
        "Ds_Merchant_UrlKO": "https://%s%s" % (site.domain, reverse('index')),
        "Ds_Merchant_Order": SermepaIdTPV.objects.new_idtpv()[-8:],
        "Ds_Merchant_TransactionType": '0',
      }

    form = SermepaPaymentForm(merchant_parameters=sermepa_dict)
    """
    #debug = True
    del request.session['cart']
    #return HttpResponse(render_to_response('ecommerce/form_sermepa.html', {'form': form, 'debug': debug}))
    #return HttpResponseRedirect('/')
    return render(request, "ecommerce/order_confirmed.html")


def order_confirmed(request, ref_token):
    order = get_object_or_404(Order, ref_token=ref_token)
    orders_products = []
    if order.status == "R":
        order.status = "C"
        order.save()

    for prod in order.products.split('/'):
        prod = prod.replace("(", "").replace(")", "").replace("L", "").split(',')
        product = get_object_or_404(product, id=prod[0])

DMCE/ecommerce/templates/ecommerce/cart.html
{% extends "CMS/main.html" %}
{% load cropping %}
{% load addcss %}

{% block title %}
<title>{{ config.name_ecomerce}} | Cesta</title>
{% endblock %}

{% block content %}

<!-- Page Loader -->        
<div class="page-loader">
<div class="loader">Loading...</div>
</div>
<!-- End Page Loader -->

<!-- Page Wrap -->
<div class="page" id="top">
<!-- Head Section -->
<section class="small-section bg-gray-lighter">
    <div class="relative container align-left">
        
        <div class="row">
            
            <div class="col-md-8">
                <h1 class="hs-line-11 font-alt mb-0">Cesta de la compra</h1>
            </div>
        </div>
        
    </div>
</section>
<!-- End Head Section -->


<!-- Section -->
<section class="page-section">
    <div class="container">
        
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                
                <table class="table table-striped shopping-cart-table">
                    <tr>
                        <th class="hidden-xs">
                            Imagen
                        </th>
                        <th>
                            Producto
                        </th>
                        <th>
                            Cantidad
                        </th>
                        <th>
                            Precio
                        </th>
                        <th>
                            
                        </th>
                    </tr>
                    <!-- cargar productos en el carro -->
                    {% for i in cart_items %}                       
                    <tr>
                        <td class="hidden-xs">
                            <img height="80" width="80" src="{{i.0.gallery.first.get_img}}" alt="foto"/>
                        </td>
                        <td>
                            <a href="#">{{i.0.title.upper}}</a>
                        </td>
                        <td>
                            <form id="form-{{i.0.id}}" method="POST" action="{% url 'ecommerce:edit_cart' %}" class="form">
                               <input name="upt_qty" type="number" class="input-sm" style="width: 60px;" min="1" max="100" value="{{i.1}}" />
                               <input type="hidden" name="update_product" value="{{i.0.id}}">
                            </form>
                        </td>
                        <td>
                            {{i.0.price}}€
                        </td>
                        <td>
                            <!-- enviar id del producto para eliminar en la view-->
                            <form method="POST" action="{% url 'ecommerce:edit_cart' %}">
                                <input type="hidden" name="del_product" value="{{i.0.id}}">

                                <button style="margin-left: 8%" type="submit" form="form-{{i.0.id}}" class="btn-gray btn-round btn-small">        
                                    <a style="text-decoration:none"><i class="fa fa-undo"></i> <span class="hidden-xs">Actualizar</span></a>
                                </button>
                                <button style="margin-left: 5%" type="submit">                 
                                    <a style="text-decoration:none"><i class="fa fa-times"></i> <span class="hidden-xs">Eliminar</span></a>
                                </button>

                            </form>
                            
                        </td>
                    </tr>
                    {% endfor %}
                </table>
                
                <hr />
                <!--
                <div class="row">
                    <div id="col-sm-4-upt_cart" class="col-sm-4 text align-right">
                        
                        <div>

                        </div>
                        
                    </div>
                </div>
                
                <hr class="mb-60" />
                -->
                <div class="row">
                    <div class="col-sm-6"></div>
                    <div class="col-sm-6 text align-right pt-10">                   
                        <div class="lead mt-0 mb-30">
                            Total pedido: <strong>{{cart_subtotal}} €</strong>
                        </div>
                        
                        <div>
                            <a href="{% url 'ecommerce:checkout' %}" class="btn btn-mod btn-round btn-large">Proceder a reserva</a>
                        </div>
                        
                    </div>
                </div>
                
                
                
            </div>
        </div>
    
    </div>
</section>
<!-- End Section -->

{% endblock content %}

DMCE/ecommerce/templates/ecommerce/general.html
{% extends "CMS/main.html" %}
{% load cropping %}
{% load addcss %}

{% block content %}

<!-- Head Section -->
<section class="page-section bg-gray-lighter" data-background="{{config.gallery.first.get_img}}">
    <div class="relative container align-left">        
        <div class="row">           
            <div class="col-md-8">
                <!-- Title category -->
                <h1 class="hs-line-11 font-alt mb-20 mb-xs-0">Tienda \ {{content.title}}</h1>
        </div>        
    </div>
</section>
<!-- End Head Section -->

<!-- Section -->
<section class="page-section">
    <div class="container relative">
        
        <div class="row">
            
            <!-- Content -->
            <div class="col-sm-12">
                
                <!-- Shop options -->
                <div class="clearfix mb-40">
                    
                    <div class="left section-text mt-10">
                        <!-- Contar productos mostrados -->
                        Mostrando {{products_cat.all.count}} resultados
                    </div>
                    
                    <!-- Filtros precio
                    <div class="right">
                        <form method="post" action="#" class="form">
                            <select class="input-md round">
                                <option>Ordenacion por defecto</option>
                                <option>Ordenar por precio: menor a mayor</option>
                                <option>Ordenar por precio: mayor a menor</option>
                            </select>
                        </form>
                    </div>
                    -->
                </div>
                <!-- End Shop options -->
                
                <div class="row multi-columns-row">
            
                    <!-- Shop Item -->
                    {% for p in products_cat %}
                    <div class="col-md-3 col-lg-3 mb-60 mb-xs-40">
                        
                        <div class="post-prev-img"> 
                            <a href="{% url 'ecommerce:dispatch_slug' p.slug %}"><img height="370" width="472" src="{{p.gallery.first.get_img}}" alt="foto" /></a>
                            {% if p.featured %}
                             <div class="intro-label">
                                <span class="label label-danger bg-red">Destacado</span>
                            </div>
                            {% endif %}   
                        </div>
                        
                        <div class="post-prev-title font-alt align-center">
                            <a href="shop-single.html">{{p.title}}</a>
                        </div>

                        <div class="post-prev-text align-center">
                            {% if p.old_price and p.old_price > p.price %}
                            <!--Precio antiguo-->
                            <del>{{p.old_price}} €</del>
                            {% endif %}
                            &nbsp;
                            <!--Precio final-->
                            <strong>{{p.price}} €</strong>
                        </div>
                        
                        <div class="post-prev-more align-center">
                            <!-- enviar post con cantidad y id de producto -->
                            <form method="POST" action="{% url 'ecommerce:edit_cart' %}">
                                <input type="hidden" name="quantity" value="1" />
                                <input type="hidden" name="add_product" value="{{p.id}}"/>                              
                                <button type="submit" class="btn btn-mod btn-gray btn-round">
                                    <a href="{% url 'ecommerce:my_cart' %}"></a>
                                    Añadir al carro
                                </button>
                            </form>
                        </div>
                        
                    </div>
                    <!-- End Shop Item -->    
                    {% endfor %}
                </div>     

            </div>
            <!-- End Content -->
        </div>       
    </div>
</section>
<!-- End Section -->
</body>
</html>


{% endblock content %}

DMCE/ecommerce/templates/ecommerce/product.html
{% extends "CMS/main.html" %}
{% load cropping %}
{% load addcss %}

{% block title %}
<title>{{ config.name_ecomerce}} | Producto</title>
{% endblock %}


{% block content %}
<!-- Head Section -->
<section class="small-section bg-gray-lighter">
    <div class="relative container align-left">   
        <div class="row">           
            <div class="col-md-8">
                <h1 class="hs-line-11 font-alt mb-20 mb-xs-0">Detalle de producto</h1>
            </div>
        </div>
        
    </div>
</section>
<!-- End Head Section -->

<!-- Section -->
<section class="page-section">
    <div class="container relative">
        
        <!-- Product Content -->
        <div class="row mb-60 mb-xs-30">
            
            <!-- Product Images -->
            <div class="col-md-4 mb-md-30">             
                <div class="post-prev-img">                     
                    <a href="{{product.gallery.get_img}}" class="lightbox-gallery-3 mfp-image"><img src="{{product.gallery.first.get_img}}" alt="foto" /></a>
                    <!-- Si el producto es destacado mostrar su correspondiente etiqueta -->
                    {% if product.featured %}
                    <div class="intro-label">
                        <span class="label label-danger bg-red">Destacado</span>
                    </div>
                    {% endif %}
                </div>
                
                <div class="row">
                    {% for img in product.gallery.all %}
                    <div class="col-xs-3 post-prev-img">
                        <a href="{{img.get_img}}" class="lightbox-gallery-3 mfp-image"><img src="{{img.get_img}}" alt="foto" /></a>
                    </div>
                    {% endfor %}
                    
                </div>
                
            </div>
            <!-- End Product Images -->
            
            <!-- Product Description -->
            <div class="col-sm-8 col-md-5 mb-xs-40">
                
                <h3 class="mt-0">{{product.title.upper}}</h3>
                
                <hr class="mt-0 mb-30"/>
                
                <div class="row">
                    <div class="col-xs-6 lead mt-0 mb-20">      
                    {% if product.old_price and product.old_price > product.price %}
                            <!--Precio antiguo-->
                            <del>{{product.old_price}} €</del>
                    {% endif %}
                    &nbsp;
                    <!--Precio final-->      
                        <strong>{{product.price}} €</strong> 
                    </div>
                    <!--
                    <div class="col-xs-6 align-right section-text">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-o"></i>
                        &nbsp;(3 reviews)
                    </div>
                    -->
                </div>
                
                <hr class="mt-0 mb-30"/> 
                <!-- Descripcion producto -->
                <div class="section-text mb-30">
                    {{product.description}}
                </div>
                
                <hr class="mt-0 mb-30"/> 
                
                <div class="mb-30">
                    <form method="POST" action="{% url 'ecommerce:edit_cart' %}" class="form">
                        {% csrf_token %}
                        <input type="number" name="quantity" class="input-lg round" min="1" max="100" value="1" />
                        <input type="hidden" name="add_product" value="{{product.id}}">
                        <button type="submit" class="btn btn-mod btn-large btn-round">                 
                            <a href="{% url 'ecommerce:my_cart' %}"></a> 
                            Añadir al carro
                        </button>
                    </form>
                </div>
                
                <hr class="mt-0 mb-30"/> 
                
                <div class="section-text small">
                    <div>Categoría: <span>{{product.category.title}}</span></div>
                </div>
                
            </div>
            <!-- End Product Description -->            
        </div>
        <!-- End Product Content -->
   
        <!-- Nav tabs -->
        {% if product.specification %}        
            <ul class="nav nav-tabs tpl-tabs animate">
                <li class="active">
                    <a href="#one" data-toggle="tab">Características</a>
                </li>
            </ul>
            <!-- End Nav tabs -->
            
            <!-- Tab panes -->
            <div class="tab-content tpl-tabs-cont">
                <div class="tab-pane fade in active" id="one">
                    {{product.specification | safe}}
                </div>
            </div>
        {% endif %}
        <!-- End Tab panes -->    
    </div>
</section>
<!-- End Section -->

{% endblock content %}

{% block extra_js %}
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $.get("/edit_cart/", function (data) {
            alert(data);
        });
    });
</script>
{% endblock extra_js %}